## 1&2

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [4]:
file_path = '/Users/anantagarwal/Downloads/wine+quality/winequality-red.csv'
data = pd.read_csv(file_path, delimiter=';')

## 3

In [7]:
X = data.drop('quality', axis=1)
y = data['quality']

## 4

In [10]:
def categorize_quality(quality):
    if quality >= 7:
        return 'best'
    elif quality >= 5:
        return 'average'
    else:
        return 'poor'

In [12]:
y = y.apply(categorize_quality)

## 5

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

## 6

In [19]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## 7

In [22]:
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [25]:
y_pred = rf_model.predict(X_test)

## 8

In [27]:
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", conf_matrix)

Confusion Matrix:
 [[321  12   0]
 [ 24  29   0]
 [ 14   0   0]]


## 9

In [30]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [32]:
print(f"Accuracy: {accuracy:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1-Score: {f1:.2f}")

Accuracy: 0.88
Precision: 0.84
Recall: 0.88
F1-Score: 0.85


## 10

In [57]:
rf_model_params = RandomForestClassifier(n_estimators=50, criterion='entropy', max_depth=10, 
                                         min_samples_split=3, min_samples_leaf=2, 
                                         max_features='sqrt', random_state=42)

In [59]:
rf_model_params.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, min_samples_leaf=2,
                       min_samples_split=3, n_estimators=50, random_state=42)

In [61]:
y_pred_params = rf_model_params.predict(X_test)

In [63]:
accuracy_params = accuracy_score(y_test, y_pred_params)
precision_params = precision_score(y_test, y_pred_params, average='weighted')
recall_params = recall_score(y_test, y_pred_params, average='weighted')
f1_params = f1_score(y_test, y_pred_params, average='weighted')

/opt/anaconda3/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [65]:
print(f"\nModified Parameters - Accuracy: {accuracy_params:.2f}")
print(f"Modified Parameters - Precision: {precision_params:.2f}")
print(f"Modified Parameters - Recall: {recall_params:.2f}")
print(f"Modified Parameters - F1-Score: {f1_params:.2f}")


Modified Parameters - Accuracy: 0.87
Modified Parameters - Precision: 0.83
Modified Parameters - Recall: 0.87
Modified Parameters - F1-Score: 0.84


## 11

In [68]:
from sklearn.tree import DecisionTreeClassifier

In [70]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [72]:
y_pred_dt = dt_model.predict(X_test)

In [74]:
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt, average='weighted')
recall_dt = recall_score(y_test, y_pred_dt, average='weighted')
f1_dt = f1_score(y_test, y_pred_dt, average='weighted')

In [76]:
print(f"\nDecision Tree - Accuracy: {accuracy_dt:.2f}")
print(f"Decision Tree - Precision: {precision_dt:.2f}")
print(f"Decision Tree - Recall: {recall_dt:.2f}")
print(f"Decision Tree - F1-Score: {f1_dt:.2f}")


Decision Tree - Accuracy: 0.81
Decision Tree - Precision: 0.84
Decision Tree - Recall: 0.81
Decision Tree - F1-Score: 0.82
